services:
  phonevalidate:
    image: ${DOCKER_REGISTRY-}phonevalidate
    build:
      context: .
      dockerfile: PhoneValidate/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=mssql,1433;Database=PhoneValidateDb;User Id=SA;Password=Senha123!;TrustServerCertificate=True
    ports:
      - "50000:8080"
    depends_on:
      mssql:
        condition: service_healthy

  mssql:
      image: mcr.microsoft.com/mssql/server:2022-latest 
      hostname: mssql
      environment:    
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Senha123!" 
      ports:
        - "1433:1433" 
      volumes:
        - mssql_data:/var/opt/mssql
      healthcheck:
        test: ["CMD-SHELL", "pidof sqlservr || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 12
        start_period: 10s

volumes:
  mssql_data: